[[redirects]]

from = "/images/full/:file"
to = "/.netlify/images?url=images/:file&fm=webp&w=800"


[[redirects]]
from = "/images/photography/:file"
to="/.netlify/images?url=images/photography/:file&fm=webp&w=800"


[[redirects]]
from = "/images/projects/:file"
to="/.netlify/images?url=images/projects/:file&fm=webp&w=800"
