# [[redirects]]
#
# from = "/images/full/:file"
# to = "/.netlify/images?url=images/:file&fm=webp&q=60"
# force = true
#
# [[redirects]
# from = "/images/photography/:file"
# to="/.netlify/images?url=images/photography/:file&fm=webp&q=60"
# force = true
#
#
# [[redirects]]
# from = "/images/projects/:file"
# to="/.netlify/images?url=images/projects/:file&fm=webp&q=60"
# force = true

# [[plugins]]
# package = "netlify-plugin-cloudinary"
#
#     [plugins.inputs]
#     cloudName = "chubi-x"
#     # imagesPath = ["/images/photography", "/images/projects"]
#     imagesPath = ["/images"]
